gha, Array.prototype.random broke node-rest-client TypeError: props[propIndex].split is not a function https://github.com/aacerox/node-rest-client/issues/154